language: node_js
node_js:
  - 0.8
  - '0.10'
before_script:
  - npm install -g grunt-cli
env:
  global:
    secure: g3kS/J7wfL2EYZjAr72ZGcR1dOzNi8eXZZxwUuO893e1QTPr17KXBwZtcYWiHHxaqURxJbW80LW7qyy3Ua5VkakdELNnzEY2uGCICzx3k8cdREo1GdhpIRmOPdjR1tg0sG4EdZrvmHkHLY0V0x2TRJnHFEuHbCESrkcR8hT3HGA=
    secure: vEPiCJVJc8x/ywpXJ/ylMOlw7t0PaeKgYx4v4UwSsVhsTZ59EI2lPGCPoXjLDQajk2IAw3ROlGygnanFhN9rafJual/oS4vcxAgnwLPLyhcxBU2Dps2K5KNjkWTgUAf6gdnpGY590l6KCYVCX+KCZkKbaXE1rijvMmbujWYhIbg=
    secure: FfhTkVHugq7f7Ac4BTNU12wAg8aN3s21G6iNommrwoQvfeNvLA3oKr/yi/OS6V1Ewl4QH8sn3RcNh+XRJBdaWEo6PE0o1Hxvja8pwNi7l5uERwqGOFVvjZDfoMnk6VaDv3FEtNPqQJkW0kp6/CtzowmxFEE82nyYke/5dHBLtZo=
